root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 500
  exclude_dir = ["tmp", "node_modules", ".git"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "html", "css", "js", "sql"]
  kill_delay = 500

[misc]
  clean_on_exit = true
